package com.tuckersoft.branchengine;
import lombok.RequiredArgsConstructor; import org.springframework.context.ApplicationEventPublisher; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.text.Normalizer; import java.time.Instant; import java.util.*;

record DecisionCommittedEvent(Long id,String simulate){}

@Service @RequiredArgsConstructor
class DecisionService {private final DecisionRepository decisions;private final PlaythroughRepository plays;private final StoryNodeRepository nodes;private final UserRepository users;private final ApplicationEventPublisher publisher;
 static String classify(String raw){String t=Normalizer.normalize(raw,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase();if(!t.matches(".*[a-z].*"))return "ENTRADA_CORRUPTA";if(has(t,"rechaza","destruye","desobedece","renuncia"))return "REBELDIA";if(has(t,"vigilan","simbolo","conspiracion"))return "SOSPECHA";if(has(t,"netflix","camara","espectador","videojuego"))return "RUPTURA_CUARTA_PARED";return "OBEDIENCIA";}
 static boolean has(String t,String...xs){return Arrays.stream(xs).anyMatch(t::contains);} static String[] derived(String b){return switch(b){case"REBELDIA"->new String[]{"Control de Continuidad","FORK_TIMELINE"};case"SOSPECHA"->new String[]{"Oficina de Seguridad","INJECT_WHITE_BEAR_SYMBOL"};case"RUPTURA_CUARTA_PARED"->new String[]{"Departamento Netflix","BREAK_FOURTH_WALL"};case"ENTRADA_CORRUPTA"->new String[]{"Archivo de Errores","DISCARD_INPUT"};default->new String[]{"Mesa de Guión","ADVANCE_MAIN_PATH"};};}
 @Transactional Decision create(DecisionRequest r,Authentication a,String simulate){if(!Set.of("LEVE","MODERADO","GRAVE","CRITICO").contains(r.impactLevel()))throw ApiProblem.bad("Impacto inválido");Playthrough p=plays.findById(r.playthroughId()).orElseThrow(()->ApiProblem.notFound("Partida no encontrada"));User actor=users.findByEmail(a.getName()).orElseThrow();if(!p.user.id.equals(actor.id)&&!"ROLE_ADMIN".equals(actor.role))throw ApiProblem.forbidden("Partida ajena");if("FINALIZADA".equals(p.status))throw ApiProblem.conflict("La partida ya terminó");Instant now=Instant.now();Decision d=new Decision();d.playthrough=p;d.node=p.currentNode;d.rawInput=r.rawInput();d.impactLevel=r.impactLevel();d.branchType=classify(r.rawInput());String[] x=derived(d.branchType);d.handlerUnit=x[0];d.outcomeCode=x[1];d.createdAt=now;d.updatedAt=now;
   int[] impact=switch(r.impactLevel()){case"LEVE"->new int[]{5,5};case"MODERADO"->new int[]{15,10};case"GRAVE"->new int[]{30,20};default->new int[]{45,40};};p.lucidity=Math.max(0,p.lucidity-impact[0]);p.controlLevel=Math.min(100,p.controlLevel+impact[1]);p.updatedAt=now;
   if("ENTRADA_CORRUPTA".equals(d.branchType)){d.status="ERROR";plays.save(p);return decisions.save(d);}
   d.resolvedNodeCode=("RUPTURA_CUARTA_PARED".equals(d.branchType)||"CRITICO".equals(d.impactLevel))?d.node.glitchBranchCode:d.node.primaryBranchCode;
   if(p.lucidity<=0){p.status="FINALIZADA";p.endingCode="ENDING_WHITE_BEAR";}else if(p.controlLevel>=100){p.status="FINALIZADA";p.endingCode="ENDING_PAC_SYMBOL";}else{StoryNode target=d.resolvedNodeCode==null?null:nodes.findByNodeCode(d.resolvedNodeCode).orElse(null);if(target==null){p.status="FINALIZADA";p.endingCode="ENDING_NETFLIX_CUT";}else p.currentNode=target;}
   plays.save(p);d.status="REGISTRADA";decisions.save(d);publisher.publishEvent(new DecisionCommittedEvent(d.id,simulate));return d;}
 Decision get(Long id,Authentication a){Decision d=decisions.findById(id).orElseThrow(()->ApiProblem.notFound("Decisión no encontrada"));canRead(d,a);return d;}
 void canRead(Decision d,Authentication a){User u=users.findByEmail(a.getName()).orElseThrow();if(!d.playthrough.user.id.equals(u.id)&&!"ROLE_ADMIN".equals(u.role))throw ApiProblem.forbidden("Decisión ajena");}
 Page<Decision> list(String b,String i,String s,Long pid,int page,int size,Authentication a){User u=users.findByEmail(a.getName()).orElseThrow();Specification<Decision> spec=(root,q,cb)->cb.equal(root.get("playthrough").get("user").get("id"),u.id);if(b!=null)spec=spec.and((r,q,c)->c.equal(r.get("branchType"),b));if(i!=null)spec=spec.and((r,q,c)->c.equal(r.get("impactLevel"),i));if(s!=null)spec=spec.and((r,q,c)->c.equal(r.get("status"),s));if(pid!=null)spec=spec.and((r,q,c)->c.equal(r.get("playthrough").get("id"),pid));return decisions.findAll(spec,PageRequest.of(Math.max(1,page)-1,Math.max(1,size),Sort.by("createdAt").descending()));}
}
