package com.tuckersoft.branchengine;
import lombok.RequiredArgsConstructor; import org.slf4j.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.CommandLineRunner; import org.springframework.context.annotation.*; import org.springframework.core.task.TaskExecutor; import org.springframework.mail.SimpleMailMessage; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.scheduling.annotation.Async; import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.*; import org.springframework.transaction.event.*; import java.time.Instant;

@Configuration class AsyncConfig {@Bean("branchExecutor") TaskExecutor branchExecutor(){ThreadPoolTaskExecutor e=new ThreadPoolTaskExecutor();e.setCorePoolSize(2);e.setMaxPoolSize(4);e.setQueueCapacity(50);e.setThreadNamePrefix("branch-worker-");e.initialize();return e;}}

@Component @RequiredArgsConstructor
class DataInitializer implements CommandLineRunner {private final UserRepository users;private final PasswordEncoder encoder;@Value("${app.admin.display-name}")String name;@Value("${app.admin.email}")String email;@Value("${app.admin.password}")String password;
 public void run(String...args){if(!users.existsByEmail(email)){User u=new User();u.email=email;u.password=encoder.encode(password);u.displayName=name;u.role="ROLE_ADMIN";u.createdAt=Instant.now();users.save(u);}}
}

@Component @RequiredArgsConstructor
class BranchNotificationListener {private static final Logger log=LoggerFactory.getLogger(BranchNotificationListener.class);private final DecisionRepository decisions;private final RealityLogRepository logs;private final JavaMailSender mail;@Value("${app.admin.email}")String adminEmail;
 @Async("branchExecutor") @Transactional(propagation=Propagation.REQUIRES_NEW) @TransactionalEventListener(phase=TransactionPhase.AFTER_COMMIT)
 public void after(DecisionCommittedEvent event){Decision d=decisions.findById(event.id()).orElseThrow();d.status="PROCESANDO";d.updatedAt=Instant.now();decisions.save(d);RealityLog r=new RealityLog();r.decision=d;r.recipientEmail=adminEmail;r.subject="[TUCKERSOFT] "+d.playthrough.playerTag+" - "+d.branchType+" (Impacto "+d.impactLevel+")";r.createdAt=Instant.now();try{if("MAIL_FAILURE".equals(event.simulate()))throw new IllegalStateException("Fallo SMTP simulado");SimpleMailMessage m=new SimpleMailMessage();m.setTo(r.recipientEmail);m.setSubject(r.subject);m.setText(body(d));mail.send(m);d.status="ESTABILIZADA";r.logStatus="SENT";r.sentAt=Instant.now();}catch(Exception e){d.status="ERROR";r.logStatus="FAILED";r.errorMessage=e.getMessage();log.error("Fallo al enviar Informe de Realidad para decisión {}",d.id,e);}d.updatedAt=Instant.now();decisions.save(d);logs.save(r);log.info("[BRANCH-LOG] Decision ID: {} | Player: {} | Branch: {} | Impact: {} | Unit: {} | Node: {} -> {} | Thread: {} | Status: {}",d.id,d.playthrough.playerTag,d.branchType,d.impactLevel,d.handlerUnit,d.node.nodeCode,d.resolvedNodeCode,Thread.currentThread().getName(),d.status);}
 String body(Decision d){Playthrough p=d.playthrough;return "Hola "+p.user.displayName+",\n\nUna partida de prueba acaba de ramificarse.\n\nDecision ID      : #"+d.id+"\nJugador          : "+p.playerTag+"\nRama             : "+d.branchType+"\nImpacto          : "+d.impactLevel+"\nDepartamento     : "+d.handlerUnit+"\nConsecuencia     : "+d.outcomeCode+"\nNodo origen      : "+d.node.nodeCode+"\nNodo destino     : "+d.resolvedNodeCode+"\nEstado partida   : "+p.status+"\nLucidez          : "+p.lucidity+"/100\nNivel de control : "+p.controlLevel+"/100\nFinal            : "+(p.endingCode==null?"-":p.endingCode)+"\nRegistrada       : "+d.createdAt+"\n\nDecisión original del jugador:\n\""+d.rawInput+"\"\n\n— Tuckersoft Branch Engine, 1984";}
}
