package com.tuckersoft.branchengine;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;

@RestController @RequestMapping("/api/v1/playthroughs") @RequiredArgsConstructor
class PlaythroughController {private final PlaythroughRepository plays;private final StoryNodeRepository nodes;private final UserRepository users;private final DecisionRepository decisions;
 User user(Authentication a){return users.findByEmail(a.getName()).orElseThrow(()->ApiProblem.notFound("Usuario no encontrado"));}
 void canRead(Playthrough p,User u){if(!p.user.id.equals(u.id)&&!"ROLE_ADMIN".equals(u.role))throw ApiProblem.forbidden("Partida ajena");}
 @PostMapping @Transactional ResponseEntity<?> create(@Valid @RequestBody PlayRequest r,Authentication a){if(plays.existsByPlayerTag(r.playerTag()))throw ApiProblem.conflict("playerTag ya existe");StoryNode n=nodes.findByNodeCode(r.startNodeCode()).orElseThrow(()->ApiProblem.notFound("Nodo inicial no encontrado"));if(n.currentBranches>=n.branchCapacity)throw ApiProblem.conflict("Nodo lleno");Instant now=Instant.now();Playthrough p=new Playthrough();p.playerTag=r.playerTag();p.user=user(a);p.startNodeCode=n.nodeCode;p.currentNode=n;p.lucidity=100;p.controlLevel=0;p.status="ACTIVA";p.createdAt=now;p.updatedAt=now;n.currentBranches++;nodes.save(n);plays.save(p);return ResponseEntity.status(201).body(Views.play(p));}
 @GetMapping Object all(Authentication a){return plays.findByUserEmailOrderByCreatedAtDesc(a.getName()).stream().map(Views::play).toList();}
 @GetMapping("/{id}") Object one(@PathVariable Long id,Authentication a){Playthrough p=plays.findById(id).orElseThrow(()->ApiProblem.notFound("Partida no encontrada"));canRead(p,user(a));return Views.play(p);}
 @GetMapping("/{id}/path") Object path(@PathVariable Long id,Authentication a){Playthrough p=plays.findById(id).orElseThrow(()->ApiProblem.notFound("Partida no encontrada"));canRead(p,user(a));List<Map<String,Object>> steps=new ArrayList<>();int i=1;for(Decision d:decisions.findByPlaythroughIdAndResolvedNodeCodeIsNotNullOrderByCreatedAtAsc(id)){Map<String,Object>m=new LinkedHashMap<>();m.put("order",i++);m.put("decisionId",d.id);m.put("fromNodeCode",d.node.nodeCode);m.put("toNodeCode",d.resolvedNodeCode);m.put("branchType",d.branchType);m.put("impactLevel",d.impactLevel);m.put("createdAt",d.createdAt);steps.add(m);}Map<String,Object>m=new LinkedHashMap<>();m.put("playthroughId",p.id);m.put("playerTag",p.playerTag);m.put("status",p.status);m.put("endingCode",p.endingCode);m.put("startNodeCode",p.startNodeCode);m.put("currentNodeCode",p.currentNode.nodeCode);m.put("steps",steps);return m;}
}
